name: Deploy to Production Server

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.5'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Build Docker image
      run: |
        docker build -t sync-pan-fe .
        docker save -o sync-pan-fe.tar sync-pan-fe

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker stop sync-pan-fe || true
          docker rm sync-pan-fe || true
          docker rmi sync-pan-fe || true
          docker load -i sync-pan-fe.tar
          docker run -d \
            --name sync-pan-fe \
            -p 80:3000 \
            -v /root/workspace/sync-pan-fe:/app \
            sync-pan-fe